default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: financial_trust_development
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "financial_trust") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

test:
  <<: *default
  database: financial_trust_test

production:
  <<: *default
  database: financial_trust_production
  username: financial_trust
  password: <%= ENV["FINANCIAL_TRUST_DATABASE_PASSWORD"] %>
